model:
  xlnet:
    class_path: permrec.model.XLNetModel
    init_args:
      d_model: 256
      n_head: 8
      d_inner: 1024
      layer_norm_eps: 1e-8
      dropout: 0.2
      activation_type: 'gelu'
      clamp_len: -1
      n_layer: 2
      num_items: 3450
      num_users: 6040
      device: 'cuda'
      initializer_range: 0.02
      
data:
  class_path: permrec.datamodule.PermRecDataModule
  init_args:
    dataset_code: 'ml-1m'
    min_rating: 0
    min_uc: 5
    min_sc: 5
    seg_len: 200
    num_seg: 2
    pred_prob: 0.8
    num_workers: 0
    test_negative_sampler_code: popular
    test_negative_sample_size: 100
    train_batch_size: 64
    val_batch_size: 64
    test_batch_size: 64

trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'Val:NDCG@10'
        patience: 20
        mode: max
  gradient_clip_val: 1.0
  gpus: '1'
  accelerator: gpu
