model:
  xlnet:
    class_path: permrec.model.XLNetModel
    init_args:
      d_model: 256
      n_head: 8
      d_inner: 1024
      layer_norm_eps: 1e-12
      dropout: 0.2
      activation_type: 'gelu'
      clamp_len: -1
      n_layer: 2
      num_items: 3450
      device: 'cuda'
      initializer_range: 0.02
  lr: 0.001
  weight_decay: 0.0

data:
  class_path: permrec.datamodule.PermRecDataModule
  init_args:
    dataset_code: 'ml-1m'
    min_rating: 0
    min_uc: 5
    min_sc: 5
    seg_len: 200
    num_train_seg: 2
    num_test_seg: 2
    pred_prob: 0.95
    num_workers: 24
    test_negative_sampler_code: popular
    test_negative_sample_size: 100
    train_batch_size: 64
    val_batch_size: 128
    test_batch_size: 128

trainer:
  default_root_dir: logs/ml-1m/+
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: 'Val:NDCG@10'
        patience: 20
        mode: max  
  gradient_clip_val: 5.0
  gpus: '6'
  accelerator: ddp
